// <auto-generated />
namespace AppCahierText.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixResponsable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixResponsable));
        
        string IMigrationMetadata.Id
        {
            get { return "202603121838219_FixResponsable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
